# Generated by Django 4.1.9 on 2023-08-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0009_arquivo_competencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo_PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
