# Generated by Django 4.1.9 on 2023-10-24 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0011_pagamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentos',
            name='arquivo_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdf.arquivo'),
        ),
        migrations.AddField(
            model_name='pagamentos',
            name='coordenadas_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamentos',
            name='coordenadas_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
