# Generated by Django 4.1.9 on 2023-09-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0005_notas_nota_cancelada_alter_basecnpj_iss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='nota_cancelada',
            field=models.BooleanField(default=False, verbose_name='Nota Cancelada?'),
        ),
    ]
